application: lokal-profil
version: 2-test
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /kmb/.*
  script: KMB.app

- url: /bbr/.*
  script: BBR.app

- url: /fmis/.*
  script: Fornminne.app

- url: /autotest/.*
  script: Autouploadtest.app

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  static_files: static/index.html
  upload: static/index\.html